#107: Fixed SLC upload and added version check
exasol/sagemaker-extension pull request #108
Opened 2024-01-18 10:58 UTC by MarleneKress79789

fixes #107 
I also added a version check. this is copy pasted from Transformers Extension so does not need in depth review

2024-01-23 10:28 UTC, Nicoretti commented on scripts/check_release_version.py
> +    assert len(latest_tag) > 0
Rather throw an exception indicating what exactly is wrong, e.g.

```python
if not latest_tag:
    raise Exception("Repository does not have any git tags.")
```

2024-01-23 10:28 UTC, Nicoretti commented on scripts/check_release_version.py
> +def get_git_version():
```suggestion
def latest_tag():
```

2024-01-23 10:28 UTC, Nicoretti commented on scripts/check_release_version.py
> +    latest_tag = tag_strings[0].strip()
if tags is empty the code will crash here before the assert is even hit.

2024-01-23 10:28 UTC, Nicoretti commented on scripts/check_release_version.py
> +def get_poetry_version():
```suggestion
def poetry_version():
```

2024-01-23 10:28 UTC, Nicoretti commented on scripts/check_release_version.py
> +def get_change_log_version():
```suggestion
def change_log_version():
```

2024-01-23 10:28 UTC, Nicoretti commented on scripts/check_release_version.py
> +    # Path overloads __truediv__
?

2024-01-24 10:13 UTC, ckunki requested changes

2024-01-25 13:02 UTC, MarleneKress79789 commented on .github/workflows/release_droid_upload_github_release_assets.yml
> +          asset_path: ${{ env.RELEASE_DIR }}/*
we do that in line 18: https://github.com/exasol/sagemaker-extension/blob/65f4e1b36a46cbcae08dcb3c2e2f91f08948b823/.github/workflows/release_droid_upload_github_release_assets.yml#L19

that should have a scope of being valid in this job only

2024-01-26 11:56 UTC, Nicoretti approved these changes

2024-01-26 11:59 UTC, MarleneKress79789 commented on scripts/check_release_version.py
> +import re
i will work on using the python toolbox probably in the next kehrwoche. as it is this file is just a copy paste of what we do in other repos until python toolbox is used everywhere. i would like to keep it as we kow it works from the other repos and keeps us from doing mistakes with the release version until we do it in a better way later.

2024-01-26 13:08 UTC, ckunki approved these changes

2024-01-26 13:08 UTC, ckunki commented on .github/workflows/release_droid_upload_github_release_assets.yml
> +          asset_path: ${{ env.RELEASE_DIR }}/*
:+1:

2024-01-26 13:08 UTC, ckunki commented on .github/workflows/release_droid_upload_github_release_assets.yml
> +          asset_path: ${{ env.RELEASE_DIR }}/*
Looking at line 42 I would think, that `$RELEASE_DIR` should also be fine. 
But let's don't get stuck on this. 
As long as it works it should be fine.

2024-01-26 13:08 UTC, ckunki commented on scripts/check_release_version.py
> +import re
:+1:

2024-01-26 13:09 UTC, merged