#60: Prepared the developer guide of SME
exasol/sagemaker-extension pull request #63
Opened 2022-02-16 14:41 UTC by umitbuyuksahin

Fixes #60

2022-02-16 14:51 UTC, tkilias requested changes

2022-02-16 14:51 UTC, tkilias commented on doc/developer_guide/developer_guide.md
> +by the help of the `regenerate_scripts.py` script executed in the `pre-commit`
Maybe add in the beginning, that the user needs to install the  githooks, after clone

2022-02-16 14:51 UTC, tkilias commented on doc/developer_guide/developer_guide.md
> +### 3. Continuous Integration (CI) Tets
We probably should call them AWS Tests, because you can also run them during development, as long you have access to AWS

2022-02-16 14:51 UTC, tkilias commented on doc/developer_guide/developer_guide.md
> +In order for these tests to run in the integration of the codes, the commit
```suggestion
In order for these tests to run in the Github Workflow, the commit 
```

2022-02-16 14:51 UTC, tkilias commented on sagemaker-extension-0.4.0-1.rockspec
> +package = "sagemaker-extension"
that is super useful

2022-02-17 09:17 UTC, morazow requested changes

2022-02-17 09:17 UTC, morazow commented on doc/developer_guide/developer_guide.md
> +```buildoutcfg
I did not know this lang support :)

2022-02-17 09:17 UTC, morazow commented on doc/developer_guide/developer_guide.md
> +installed on the development  machine.
```suggestion
installed on the development machine.
```

2022-02-17 09:17 UTC, morazow commented on doc/developer_guide/developer_guide.md
> +
```suggestion
```

2022-02-17 09:17 UTC, morazow commented on doc/developer_guide/developer_guide.md
> +scripts but also perform static code analysis.
```suggestion
scripts but also performs static code analysis.
```

2022-02-17 09:17 UTC, morazow commented on doc/developer_guide/developer_guide.md
> +the real AWS services. Therefore, you must set AWS credentials in the os
```suggestion
the real AWS services. Therefore, you must set AWS credentials in the OS 
```

2022-02-17 09:17 UTC, morazow commented on doc/developer_guide/developer_guide.md
> +the `ci-tests`;  as a result of that not  all the tests can be validated. In
```suggestion
the `ci-tests`; as a result of that not all the tests can be validated. In 
```

2022-02-17 09:26 UTC, morazow submitted a review, later dismissed

2022-02-17 10:05 UTC, MarleneKress79789 commented on doc/developer_guide/developer_guide.md
> +the `ci-tests`;  as a result of that not  all the tests can be validated. In
```suggestion
the `ci-tests`;  as a result of that, not  all the tests can be validated. In 
```

2022-02-17 10:06 UTC, MarleneKress79789 commented on doc/developer_guide/developer_guide.md
> +order not to miss this situation, we deliberately get GitHub-workflows failed.
```suggestion
order not to miss this situation, we deliberately let GitHub-workflows fail. 
```
Might be better?

2022-02-17 11:03 UTC, tkilias requested changes

2022-02-17 11:03 UTC, tkilias commented on doc/developer_guide/developer_guide.md
> +### 3. AWS Tets
```suggestion
### 3. AWS Tests
```

2022-02-17 14:30 UTC, morazow approved these changes

2022-02-17 14:31 UTC, merged